# -*- coding: utf-8 -*-
"""a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uVXtvexamfxtQhNcUeZdo_fUof2jmRam
"""

import xml.etree.ElementTree as ET
import pandas as pd

week_days = [] 
titles = []
k_calories = []
file = 'items1'

tree = ET.parse("Cardapio\\"+str(file)+".txt")
root = tree.getroot()
#week = '2022-11-14'

ns = ''
if '{' in root.tag:
    ns = '{'+root.tag.split('}')[0].strip('{')+'}'

for entry in root.findall(f'{ns}entry'):
    properties = entry.find(f'{ns}content').find('{http://schemas.microsoft.com/ado/2007/08/dataservices/metadata}properties')
    week_days.append(properties.find('{http://schemas.microsoft.com/ado/2007/08/dataservices}DiaSemana').text)
    titles.append(properties.find('{http://schemas.microsoft.com/ado/2007/08/dataservices}Title').text)
    k_calories.append(int(properties.find('{http://schemas.microsoft.com/ado/2007/08/dataservices}Kcal').text))

df2 = pd.DataFrame({'week_day': week_days, 'title': titles, 'k_calories': k_calories})
#print(df2)
try:
    df1 = pd.read_csv(str(file)+'.csv')
    df = pd.concat([df1,df2],ignore_index=True).reset_index(drop=True)
except:
    df = df2

weekday_sort = {'Segunda':0, 'Terca':1, 'Quarta':2, 'Quinta':3, 'Sexta':4}

df = df.sort_values(by=['week_day','k_calories'],key=lambda x: x.map(weekday_sort))
print(df[df['week_day']=='Segunda'])

sums = df.groupby("week_day").sum('k_calories')
print(sums)

df.to_csv("Cardapio\\"+str(file)+'.csv',index=False)
print(len(df))


